(ns y-video-back.db.content-subtitles-assoc
  (:require [y-video-back.db.core :as db]))

(def CREATE (partial db/CREATE :content-subtitles-assoc))
(def READ  (partial db/READ :content-subtitles-assoc-undeleted))
(def READ-ALL  (partial db/READ :content-subtitles-assoc))
(def UPDATE (partial db/UPDATE :content-subtitles-assoc))
(def DELETE (partial db/mark-deleted :content-subtitles-assoc))
(def CLONE (partial db/CLONE :content-subtitles-assoc))
(def PERMANENT-DELETE (partial db/DELETE :content-subtitles-assoc))
(def READ-BY-IDS "[column-vals & select-field-keys]\ncolumn-vals must be a content containing content-id then subtitle-id. select-field-keys, if given, must be a content containing keywords representing columns to return from db." (partial db/read-where-and :content-subtitles-assoc-undeleted [:content-id :subtitle-id]))
(def DELETE-BY-IDS "[column-vals]\ncolumn-vals must be a content containing content-id then subtitle-id." (partial db/delete-where-and :content-subtitles-assoc-undeleted [:content-id :subtitle-id]))
(def READ-SUBTITLES-BY-CONTENT (partial db/read-all-where :subtitles-by-content :content-id))
(def READ-CONTENTS-BY-SUBTITLE (partial db/read-all-where :contents-by-subtitle :subtitle-id))
(defn EXISTS-CONT-SBTL? [content-id subtitle-id] (seq (db/read-where-and :content-subtitles-assoc-undeleted [:content-id :subtitle-id] [content-id subtitle-id])))
