(ns y-video-back.db.contents
  (:require [y-video-back.db.core :as db]))

(def CREATE (partial db/CREATE :contents))
(def READ  (partial db/READ :contents-undeleted))
(def READ-ALL  (partial db/READ :contents))
(def UPDATE (partial db/UPDATE :contents))
(def DELETE (partial db/mark-deleted :contents))
(def CLONE (partial db/CLONE :contents))
(def PERMANENT-DELETE (partial db/DELETE :contents))
(def READ-BY-IDS (partial db/read-where-and :contents-undeleted [:collection-id :resource-id]))
(def DELETE-BY-IDS "[column-vals]\ncolumn-vals must be a collection containing collection-id then resource-id." (partial db/delete-where-and :contents-undeleted [:collection-id :resource-id]))
(def READ-CONTENTS-BY-COLLECTION (partial db/read-all-where :resources-by-collection :collection-id))
(def READ-COLLECTIONS-BY-CONTENT (partial db/read-all-where :collections-by-resource :resource-id))
(defn EXISTS-COLL-CONT? [collection-id resource-id] (not (empty? (db/read-where-and :contents-undeleted [:collection-id :resource-id] [collection-id resource-id]))))
(defn EXISTS? [id] (not (nil? (db/READ :contents-undeleted id))))
