DROP TABLE IF EXISTS TWord;
--;;
DROP TABLE IF EXISTS Account_Collection;
--;;
DROP TABLE IF EXISTS Collection_Course;
--;;
DROP TABLE IF EXISTS Collection_Content;
--;;
DROP TABLE IF EXISTS Content_File;
--;;
DROP TABLE IF EXISTS Account;
--;;
DROP TABLE IF EXISTS Collection;
--;;
DROP TABLE IF EXISTS Course;
--;;
DROP TABLE IF EXISTS Content;
--;;
DROP TABLE IF EXISTS File;
--;;
DROP EXTENSION IF EXISTS "pgcrypto";
--;;
DROP FUNCTION IF EXISTS uuid_generate_v4;
--;;
