name: Clojure CI

on:
  pull_request:
  push:
    branches: [ development ]

env:
  FILE_NAME: "env/test/resources/config.edn"

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: yvideo_test
          POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_USER }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - run: docker ps -a

    - uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - run: git clone https://github.com/BYU-ODH/yvideo-client.git

    - name: Install ffmpeg / ffmprob
      run: sudo apt-get update && sudo apt-get install ffmpeg

    - name: Install node dependencies for front-end
      working-directory: ./yvideo-client
      run: |
        git checkout develop
        npm install

    - name: Build Front-end
      env:
        CI: ""
      run: ./build-front-end.sh

    - name: Create File with content
      run: echo ${{ secrets.TEST_CONFIG }} | base64 -d | sed "s/ 5000/ 10000/g" > ${FILE_NAME}

    - name: Install dependencies
      run: lein deps

    - name: Create Testing Folders
      working-directory: ./test/clj/
      run: |
        mkdir -p testing/{dest,trash,temp,src,log}

    - name: Run tests
      run: docker ps -a && lein with-profile test cloverage
      env:
        PGUSER: ${{ secrets.TEST_DB_USER }}
